"use client";

import { Brain, Calendar, Clock, User, BarChart3, BookOpen, AlertCircle, CheckCircle, FileText } from "lucide-react";

const upcomingSessions = [
  {
    client: "BotswanaPower Ltd",
    contact: "Tebogo Kgalagadi",
    service: "Strategy Execution Workshop",
    date: "Mon 14 Apr",
    time: "09:00",
    duration: "2 days",
    type: "In-Person",
    priority: "HIGH",
    color: "#EF4444",
  },
  {
    client: "Capital Bank Botswana",
    contact: "Dr. Masego Sithembi",
    service: "Governance Diagnostic",
    date: "Wed 16 Apr",
    time: "14:00",
    duration: "60 min",
    type: "Video",
    priority: "HIGH",
    color: "#EF4444",
  },
  {
    client: "African Growth Partners",
    contact: "Keitseng Molefhe",
    service: "OKR Implementation Advisory",
    date: "Thu 17 Apr",
    time: "10:00",
    duration: "90 min",
    type: "Video",
    priority: "MEDIUM",
    color: "#F59E0B",
  },
];

const briefingNotes = [
  {
    client: "BotswanaPower Ltd",
    industry: "Energy & Utilities",
    size: "500–1000 employees",
    session: "Strategy Execution Workshop",
    score: 52,
    dimension: "Execution",
    toolkits: ["Strategy Execution Toolkit", "Corporate Governance Framework"],
    keyGaps: [
      "No formal PMO structure — projects managed ad hoc",
      "Strategy document exists but departmental cascading is missing",
      "Board oversight of major projects is informal",
    ],
    focusAreas: [
      "Establish execution governance framework",
      "Define top 5 strategic priorities for FY2026",
      "Build 90-day sprint plan with accountability owners",
    ],
    aiNote: "Client scored lowest in Execution (52%) and Governance (55%). They have a strong strategic intent but poor execution infrastructure. Recommend leading with PMO setup and RACI matrix development in the workshop.",
  },
];

export default function ConsultantView() {
  return (
    <div className="fade-in-up">
      {/* AI Briefing header */}
      <div style={{
        background: "linear-gradient(135deg, rgba(59,194,251,0.08), rgba(0,123,95,0.06))",
        border: "1px solid rgba(59,194,251,0.2)", borderRadius: 14, padding: "18px 22px", marginBottom: 24,
        display: "flex", alignItems: "center", gap: 14,
      }}>
        <div className="agent-pulse" style={{
          width: 42, height: 42, borderRadius: 12,
          background: "linear-gradient(135deg, #3BC2FB, #007B5F)",
          display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0,
        }}>
          <Brain size={20} color="#0F1419" />
        </div>
        <div>
          <div style={{ fontSize: 12, color: "#3BC2FB", fontFamily: "Montserrat, sans-serif", fontWeight: 700, marginBottom: 4 }}>
            CONSULTANT BRIEFING AGENT — ACTIVE
          </div>
          <div style={{ fontSize: 13, color: "#E5E7EB" }}>
            You have <strong style={{ color: "#fff" }}>3 sessions</strong> this week. AI-generated briefings are ready for all upcoming clients. No discovery fatigue — walk in already aligned.
          </div>
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 340px", gap: 20 }}>
        {/* Main: Briefing Notes */}
        <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
          <div style={{ backgroundColor: "#1A1F2E", border: "1px solid #374151", borderRadius: 14, padding: 22 }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }}>
              <h3 style={{ margin: 0, fontFamily: "Montserrat, sans-serif", fontSize: 14 }}>AI Pre-Session Briefings</h3>
              <div style={{ fontSize: 12, color: "#9CA3AF" }}>Generated by Uhuru AI · Baobab 3.0</div>
            </div>

            {briefingNotes.map((brief, i) => (
              <div key={i} style={{
                backgroundColor: "#252B3A", borderRadius: 14, padding: 22,
                border: "1px solid #374151", marginBottom: 14,
              }}>
                {/* Client header */}
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 18 }}>
                  <div>
                    <h4 style={{ margin: "0 0 4px", fontFamily: "Montserrat, sans-serif", fontSize: 16 }}>{brief.client}</h4>
                    <div style={{ display: "flex", gap: 10, fontSize: 12, color: "#9CA3AF" }}>
                      <span>{brief.industry}</span>
                      <span>·</span>
                      <span>{brief.size}</span>
                    </div>
                  </div>
                  <button style={{
                    display: "flex", alignItems: "center", gap: 6, padding: "7px 14px",
                    background: "rgba(59,194,251,0.1)", border: "1px solid rgba(59,194,251,0.2)",
                    borderRadius: 8, color: "#3BC2FB", cursor: "pointer", fontSize: 12,
                    fontFamily: "Montserrat, sans-serif", fontWeight: 600,
                  }}>
                    <FileText size={12} /> Export Briefing
                  </button>
                </div>

                {/* Score highlight */}
                <div style={{
                  background: "rgba(239,68,68,0.08)", border: "1px solid rgba(239,68,68,0.2)",
                  borderRadius: 10, padding: "12px 16px", marginBottom: 18,
                  display: "flex", alignItems: "center", gap: 14,
                }}>
                  <AlertCircle size={18} color="#EF4444" />
                  <div>
                    <div style={{ fontSize: 12, color: "#EF4444", fontFamily: "Montserrat, sans-serif", fontWeight: 700 }}>CRITICAL GAP</div>
                    <div style={{ fontSize: 13, color: "#E5E7EB" }}>
                      {brief.dimension} maturity at <strong style={{ color: "#EF4444" }}>{brief.score}%</strong> — below the 65% benchmark. This is the primary driver for today's session.
                    </div>
                  </div>
                </div>

                {/* Toolkits used */}
                <div style={{ marginBottom: 18 }}>
                  <div style={{ fontSize: 12, color: "#6B7280", marginBottom: 8, fontFamily: "Montserrat, sans-serif", fontWeight: 600 }}>TOOLKITS DOWNLOADED</div>
                  <div style={{ display: "flex", gap: 8 }}>
                    {brief.toolkits.map(tk => (
                      <div key={tk} style={{
                        display: "flex", alignItems: "center", gap: 6,
                        padding: "6px 12px", borderRadius: 8,
                        backgroundColor: "rgba(59,194,251,0.08)", border: "1px solid rgba(59,194,251,0.15)",
                        fontSize: 12, color: "#3BC2FB",
                      }}>
                        <BookOpen size={12} /> {tk}
                      </div>
                    ))}
                  </div>
                </div>

                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 18 }}>
                  {/* Key Gaps */}
                  <div>
                    <div style={{ fontSize: 12, color: "#6B7280", marginBottom: 10, fontFamily: "Montserrat, sans-serif", fontWeight: 600 }}>KEY GAPS IDENTIFIED</div>
                    <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                      {brief.keyGaps.map((gap, gi) => (
                        <div key={gi} style={{ display: "flex", gap: 8, alignItems: "flex-start" }}>
                          <AlertCircle size={13} color="#EF4444" style={{ flexShrink: 0, marginTop: 1 }} />
                          <span style={{ fontSize: 12, color: "#E5E7EB", lineHeight: 1.4 }}>{gap}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Recommended Focus */}
                  <div>
                    <div style={{ fontSize: 12, color: "#6B7280", marginBottom: 10, fontFamily: "Montserrat, sans-serif", fontWeight: 600 }}>RECOMMENDED FOCUS AREAS</div>
                    <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                      {brief.focusAreas.map((area, ai) => (
                        <div key={ai} style={{ display: "flex", gap: 8, alignItems: "flex-start" }}>
                          <CheckCircle size={13} color="#22C55E" style={{ flexShrink: 0, marginTop: 1 }} />
                          <span style={{ fontSize: 12, color: "#E5E7EB", lineHeight: 1.4 }}>{area}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>

                {/* AI Note */}
                <div style={{
                  background: "linear-gradient(135deg, rgba(59,194,251,0.06), rgba(0,123,95,0.04))",
                  border: "1px solid rgba(59,194,251,0.15)", borderRadius: 10, padding: 14,
                }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}>
                    <Brain size={13} color="#3BC2FB" />
                    <span style={{ fontSize: 11, color: "#3BC2FB", fontFamily: "Montserrat, sans-serif", fontWeight: 700 }}>UHURU AI CONSULTANT NOTE</span>
                  </div>
                  <p style={{ margin: 0, fontSize: 12, color: "#9CA3AF", lineHeight: 1.6 }}>{brief.aiNote}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Right: Upcoming Sessions */}
        <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
          <div style={{ backgroundColor: "#1A1F2E", border: "1px solid #374151", borderRadius: 14, padding: 20 }}>
            <h4 style={{ margin: "0 0 18px", fontFamily: "Montserrat, sans-serif", fontSize: 13 }}>Upcoming Sessions</h4>
            <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
              {upcomingSessions.map((session, i) => (
                <div key={i} style={{
                  backgroundColor: "#252B3A", borderRadius: 12, padding: 16,
                  border: `1px solid ${session.color}18`,
                }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 10 }}>
                    <div style={{ fontSize: 13, fontFamily: "Montserrat, sans-serif", fontWeight: 700, color: "#fff", lineHeight: 1.3 }}>
                      {session.client}
                    </div>
                    <span style={{
                      padding: "2px 7px", borderRadius: 5, fontSize: 10,
                      backgroundColor: `${session.color}15`, color: session.color,
                      fontFamily: "Montserrat, sans-serif", fontWeight: 700,
                    }}>
                      {session.priority}
                    </span>
                  </div>
                  <div style={{ fontSize: 12, color: "#9CA3AF", marginBottom: 8 }}>{session.service}</div>
                  <div style={{ display: "flex", gap: 12, fontSize: 12, color: "#9CA3AF" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
                      <Calendar size={11} /> {session.date}
                    </div>
                    <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
                      <Clock size={11} /> {session.time}
                    </div>
                    <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
                      <User size={11} /> {session.type}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Consultant Stats */}
          <div style={{ backgroundColor: "#1A1F2E", border: "1px solid #374151", borderRadius: 14, padding: 20 }}>
            <h4 style={{ margin: "0 0 16px", fontFamily: "Montserrat, sans-serif", fontSize: 13 }}>Your Performance</h4>
            {[
              { label: "Sessions This Month", value: "12", icon: Calendar, color: "#3BC2FB" },
              { label: "Client Satisfaction", value: "4.9/5", icon: BarChart3, color: "#007B5F" },
              { label: "Conversion Rate", value: "74%", icon: CheckCircle, color: "#22C55E" },
              { label: "Revenue Generated", value: "BWP 128K", icon: Brain, color: "#8B5CF6" },
            ].map((item, i) => {
              const Icon = item.icon;
              return (
                <div key={i} style={{
                  display: "flex", justifyContent: "space-between", alignItems: "center",
                  padding: "10px 0", borderBottom: "1px solid #252B3A",
                }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    <Icon size={14} color={item.color} />
                    <span style={{ fontSize: 12, color: "#9CA3AF" }}>{item.label}</span>
                  </div>
                  <span style={{ fontSize: 14, fontFamily: "Montserrat, sans-serif", fontWeight: 700, color: "#fff" }}>{item.value}</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
